//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPANHA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPANHA()
        {
            this.CAMPANHA_CONTATO = new HashSet<CAMPANHA_CONTATO>();
            this.CAMPANHA_GRUPO = new HashSet<CAMPANHA_GRUPO>();
            this.TEMPLATE = new HashSet<TEMPLATE>();
            this.MENSAGEM_CAMPANHA = new HashSet<MENSAGEM_CAMPANHA>();
        }
    
        public int CAMP_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string CAMP_NM_NOME { get; set; }
        public System.DateTime CAMP_DT_INICIO { get; set; }
        public Nullable<System.DateTime> CAMP_DT_FINAL { get; set; }
        public string CAMP_DS_DESCRICAO { get; set; }
        public int CAMP_IN_ATIVO { get; set; }
        public Nullable<int> CONT_CD_ID { get; set; }
        public Nullable<int> GRUP_CD_ID { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPANHA_CONTATO> CAMPANHA_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPANHA_GRUPO> CAMPANHA_GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPLATE> TEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGEM_CAMPANHA> MENSAGEM_CAMPANHA { get; set; }
    }
}
