//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTATO()
        {
            this.CAMPANHA_CONTATO = new HashSet<CAMPANHA_CONTATO>();
            this.GRUPO_CONTATO = new HashSet<GRUPO_CONTATO>();
            this.MENSAGEM_CONTATO = new HashSet<MENSAGEM_CONTATO>();
            this.MENSAGEM = new HashSet<MENSAGEM>();
        }
    
        public int CONT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string CONT_NM_NOME { get; set; }
        public string CONT_NR_WHATSAPP { get; set; }
        public string CONT_NR_WHATSAPP2 { get; set; }
        public Nullable<int> ORIG_CD_ID { get; set; }
        public string CONT_NM_CARGO { get; set; }
        public Nullable<int> CACO_CD_ID { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string CACO_NM_CIDADE { get; set; }
        public Nullable<int> PROF_CD_ID { get; set; }
        public Nullable<System.DateTime> CONT_DT_NASCIMENTO { get; set; }
        public Nullable<int> CLUB_CD_ID { get; set; }
        public string CONT_DS_DETALHES { get; set; }
        public string CONT_NM_EMAIL { get; set; }
        public string CONT_NR_TELEFONE { get; set; }
        public string CONT_NR_CELULAR { get; set; }
        public Nullable<int> CONT_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPANHA_CONTATO> CAMPANHA_CONTATO { get; set; }
        public virtual CATEGORIA_CONTATO CATEGORIA_CONTATO { get; set; }
        public virtual CLUBE CLUBE { get; set; }
        public virtual ORIGEM ORIGEM { get; set; }
        public virtual PROFISSAO PROFISSAO { get; set; }
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_CONTATO> GRUPO_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGEM_CONTATO> MENSAGEM_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGEM> MENSAGEM { get; set; }
    }
}
